### ISSUE TITLE
build.js 실행했을때 오류

### ISSUE THREAD

**Issue by kdwkr** [ChalkPE/facebook-autopoker#1]
PS C:\Users\KimDaewoon\Desktop\facebook-autopoker-master> node build.js
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'C:\Users\KimDaewoon\Desktop\facebook-autopoker-master\dist\bundle.js'
    at Error (native)

**Comment by chalkpe** [comment]
`devDependencies`에 browserify 넣어 두고 `--production` 붙이라고 써 놨네요 ㅋㅋㅋㅋㅋ
내일 고쳐놓을게요! 일단은 그냥 `npm install` 치고 다시 해 보세요
